version: '3.8'

services:
  quarkus-app:
    build: ../.
    ports:
      - "8080:8080"
    environment:
      - DB_KIND=postgresql
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}
    depends_on:
      - db
    networks:
      - internal-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge

volumes:
  postgres_data: