
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            # Step 2: Set up Docker
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            # Step 3: Log in to Docker Hub (or GitHub Container Registry)
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME || 'default-username' }}
                password: ${{ secrets.DOCKER_PASSWORD || 'default-password' }}

             # Step 4: Determine version tag dynamically
            - name: Determine image tag
              id: versioning
              run: |
                if [ "${{ github.ref }}" == "refs/heads/main" ]; then
                    echo "tag=latest" >> $GITHUB_ENV
                else
                    BRANCH_NAME=$(echo "${{ github.ref_name }}" | tr '/' '-')
                    echo "tag=$BRANCH_NAME" >> $GITHUB_ENV
                fi
                echo "version=commit-${{ github.sha }}" >> $GITHUB_ENV

            # Step 4: Build and push the Docker image
            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                push: true
                tags: |
                    pauloferreiradeoliveira/fiapposlanchonete:latest
                    pauloferreiradeoliveira/fiapposlanchonete:${{ env.tag }}
                    pauloferreiradeoliveira/fiapposlanchonete:${{ env.version }}
                context: .
            


            